steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Build the React app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Copy build output to the "build" folder expected by App Engine
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p ./appengine-build && cp -r build/* ./appengine-build/

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']
    dir: 'appengine-build'

timeout: '900s'
